### ISSUE TITLE
Qr/Barcode fuctionality

### ISSUE THREAD

**Issue by menno-m** [doo/Scanbot-SDK-Examples#16]
Hi,

Im trying out your SDK. So far im able to test all the functionality which is covered in the Wiki pages. But i would also like to test the QR and barcode scanning capabilities that are mentioned on the Scanbot.io website. I see no reference in the documentation at http://doo.github.io/Scanbot-SDK-Documentation/Android/ to QR/barcodes either. Could you point me out where i can find that functionality?

**Comment by dmitry-zaitsev** [comment]
Hi,

Sorry, this information is outdated and will be removed from the website. We do not have QR/Barcode scanning capabilities in our SDK. The reason is as simple as - there are great free libraries which you can use instead (such as ZXing for Android). If needed, you can easily attach them to our camera SDK.

**Comment by menno-m** [comment]
Ok thank you, clear answer
